# Generated by Django 3.2.13 on 2022-04-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='previous',
        ),
    ]
