# Generated by Django 3.2.13 on 2022-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_remove_reservation_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_reservation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
