# Generated by Django 3.2.13 on 2022-04-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_reservation_previous_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_reservation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
