# Generated by Django 3.2.13 on 2022-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_alter_reservation_previous_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
