# Generated by Django 3.2.13 on 2022-04-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0006_alter_reservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_rental', to='guestapp.rental')),
                ('pre_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_reservation', to='guestapp.rental')),
            ],
        ),
    ]
