# Generated by Django 3.2.13 on 2022-04-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0008_alter_previous_reservation_pre_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='guestapp.rental'),
        ),
    ]
