# Generated by Django 3.2.13 on 2022-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0010_auto_20220428_0338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Previous_reservation',
        ),
    ]
